/**
 * apex-discovery Pi Coding Agent Config Generator
 *
 * Generates Pi configuration files for multi-agent orchestration,
 * safety rules, and agent definitions.
 */

import { existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const PI_DIR = '.pi';

function ensurePiDir(sub) {
  const dir = join(process.cwd(), PI_DIR, sub);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  return dir;
}

/** Generate Pi agent team config from apex agents */
export function generateTeamConfig(agents = []) {
  const dir = ensurePiDir('agents');
  const teams = {
    teams: {
      'apex-dev': {
        agents: agents.slice(0, 5).map(a => a.name || a)
      }
    }
  };
  const path = join(dir, 'teams.yaml');
  const yaml = `# Generated by apex-discovery
teams:
  apex-dev:
    agents: [${teams.teams['apex-dev'].agents.join(', ')}]
`;
  writeFileSync(path, yaml, 'utf8');
  return { path, team: 'apex-dev', agents: teams.teams['apex-dev'].agents };
}

/** Generate Pi agent chain config from apex phases */
export function generateChainConfig() {
  const dir = ensurePiDir('agents');
  const steps = [
    { agent: 'planner', prompt: 'Plan the implementation: $INPUT' },
    { agent: 'builder', prompt: 'Implement the plan step by step. Context: $INPUT' },
    { agent: 'reviewer', prompt: 'Review the implementation for correctness and quality. Code: $INPUT' }
  ];
  const yaml = `# Generated by apex-discovery
steps:
${steps.map(s => `  - agent: ${s.agent}\n    prompt: "${s.prompt}"`).join('\n')}
`;
  const path = join(dir, 'agent-chain.yaml');
  writeFileSync(path, yaml, 'utf8');
  return { path, steps: steps.length };
}

/** Generate Pi damage-control safety rules using apex safety-guard patterns */
export function generateDamageControl() {
  const dir = ensurePiDir('');
  const rules = {
    dangerousCommands: [
      { pattern: 'rm\\s+-rf\\s+(/|~|\\*)', block: true, reason: 'Would delete root/home/all' },
      { pattern: 'git\\s+reset\\s+--hard', block: false, ask: true, reason: 'Would discard uncommitted changes' },
      { pattern: 'DROP\\s+DATABASE', block: true, reason: 'Would drop a database' },
      { pattern: '>\\s*/dev/(sda|sdb|nvme)', block: true, reason: 'Would overwrite block device' },
    ],
    zeroAccess: [
      '.env', '.env.*', '~/.ssh/', '*.pem', 'credentials.json', 'config/defaults.json'
    ],
    readOnly: [
      'package-lock.json', 'yarn.lock', '.gitignore'
    ],
    noDelete: [
      '.git/', 'README.md', 'LICENSE', 'Dockerfile', 'docker-compose.yml'
    ]
  };

  const yaml = `# Generated by apex-discovery
# Pi damage-control safety rules

dangerousCommands:
${rules.dangerousCommands.map(r =>
  `  - pattern: "${r.pattern}"\n    block: ${r.block}${r.ask ? '\n    ask: true' : ''}\n    reason: "${r.reason}"`
).join('\n')}

zeroAccess:
${rules.zeroAccess.map(p => `  - "${p}"`).join('\n')}

readOnly:
${rules.readOnly.map(p => `  - "${p}"`).join('\n')}

noDelete:
${rules.noDelete.map(p => `  - "${p}"`).join('\n')}
`;
  const path = join(dir, 'damage-control-rules.yaml');
  writeFileSync(path, yaml, 'utf8');
  return { path, rules: Object.keys(rules).length };
}

/** Setup Pi project with all config files */
export function setupPiAll(agents = []) {
  const results = {
    team: generateTeamConfig(agents),
    chain: generateChainConfig(),
    damage: generateDamageControl(),
  };
  return results;
}
